### ISSUE TITLE
Provide multilib support

### ISSUE THREAD

**Issue by voltur01** [ARM-software/LLVM-embedded-toolchain-for-Arm#110]
Multilib toolchains contain multiple sysroot, each having a version of the target libraries for different architecture/ABI variants that are selected based on the target and other command line options.

Now users have to specify `--config` option to explicitly select the library variant.

**Comment by mplatings** [comment]
Addressed by #212 on the llvm-16 branch.

**Comment by mplatings** [comment]
Addressed by #250 on the main branch.
