### ISSUE TITLE
how to use static base register r9?

### ISSUE THREAD

**Issue by versaloon** [ARM-software/LLVM-embedded-toolchain-for-Arm#115]
I want to compile a source code with PIC + static base r9 register.
For GCC, I use commands below:
`
PS Z:\elfloader> cat main.c
static int __local_cnt = 1;
static int __local_idx;
extern int printf(const char *format, ...);
int main(int argc, char *argv[])
{
    __local_cnt++;
    __local_idx = 1;
    printf("test: %d %d\n", __local_cnt, __local_idx);
    return 0;
}
PS Z:\elfloader> arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -fPIC -msingle-pic-base -mpic-register=r9 -mno-pic-data-is-text-relative -Wall -g -O2 -c main.c -o main.o
PS Z:\elfloader> arm-none-eabi-gcc -shared -fPIC -msingle-pic-base -mpic-register=r9 -mno-pic-data-is-text-relative -nostdlib -o main.elf main.o
PS Z:\elfloader> arm-none-eabi-objdump -S main.elf

main.elf:     file format elf32-littlearm

Disassembly of section .plt:

0000014c <.plt>:
 14c:   b500            push    {lr}
 14e:   f8df e008       ldr.w   lr, [pc, #8]    ; 158 <.plt+0xc>
 152:   44fe            add     lr, pc
 154:   f85e ff08       ldr.w   pc, [lr, #8]!
 158:   000100dc        .word   0x000100dc

0000015c <printf@plt>:
 15c:   f240 0cd8       movw    ip, #216        ; 0xd8
 160:   f2c0 0c01       movt    ip, #1
 164:   44fc            add     ip, pc
 166:   f8dc f000       ldr.w   pc, [ip]
 16a:   e7fc            b.n     166 <printf@plt+0xa>

Disassembly of section .text:

0000016c <main>:
static int __local_cnt = 1;
static int __local_idx;
extern int printf(const char *format, ...);
int main(int argc, char *argv[])
{
 16c:   b508            push    {r3, lr}
    __local_cnt++;
 16e:   4a07            ldr     r2, [pc, #28]   ; (18c <main+0x20>)
    __local_idx = 1;
    printf("test: %d %d\n", __local_cnt, __local_idx);
 170:   4b07            ldr     r3, [pc, #28]   ; (190 <main+0x24>)
    __local_cnt++;
 172:   f859 0002       ldr.w   r0, [r9, r2]
 176:   6801            ldr     r1, [r0, #0]
    printf("test: %d %d\n", __local_cnt, __local_idx);
 178:   2201            movs    r2, #1
    __local_cnt++;
 17a:   4411            add     r1, r2
 17c:   6001            str     r1, [r0, #0]
    printf("test: %d %d\n", __local_cnt, __local_idx);
 17e:   f859 0003       ldr.w   r0, [r9, r3]
 182:   f7ff ffeb       bl      15c <printf@plt>
    return 0;
 186:   2000            movs    r0, #0
 188:   bd08            pop     {r3, pc}
 18a:   bf00            nop
 18c:   00000014        .word   0x00000014
 190:   00000010        .word   0x00000010
`

But there is BUG in arm-none-eabi-gcc while processing code in plt sections, whick still use PC + offset instead of R9 to obtain GOT address.

For llvm, it seems the options are different:
`
PS Z:\elfloader> E:\Software\armllvm\bin\clang.exe --config armv6m_soft_nofp_nosys -mcpu=cortex-m4 -mthumb -fPIC -msingle-pic-base -mpic-register=r9 -mno-pic-data-is-text-relative -Wall -g -O2 -c main.c -o main.o
clang: error: unknown argument: '-msingle-pic-base'
clang: error: unknown argument: '-mpic-register=r9'
clang: error: unknown argument: '-mno-pic-data-is-text-relative'
`
It seems -nostdlib and -shared are not available in llvm too?

I checked the docs here: https://developer.arm.com/documentation/100748/0612.
But can not find the corresponding options.

**Comment by mplatings** [comment]
I'm not an expert but I'm not aware of clang having equivalents of GCC's PIC configuration options. This seems to be a clang question rather than something for this project so I recommend asking in https://discourse.llvm.org/
