### ISSUE TITLE
Support kasan for arm-none-unknown-eabi'

### ISSUE THREAD

**Issue by anjiahao1** [ARM-software/LLVM-embedded-toolchain-for-Arm#293]
clang-16: error: unsupported option '-fsanitize=kernel-address' for target 'arm-none-unknown-eabi', gcc is support arm-none-unknown-eabi

**Comment by mplatings** [comment]
Yes, judging by the [Clang address sanitizer docs](https://clang.llvm.org/docs/AddressSanitizer.html#supported-platforms) that's not supported by Clang. It's something that can be changed from this project, sorry.
