### ISSUE TITLE
patch filename in CmakeList.txt

### ISSUE THREAD

**Issue by Laur59** [ARM-software/LLVM-embedded-toolchain-for-Arm#342]
Hi all!
First thanks for the work bringing LLVM to embedded ARM processors.
CMakeList.txt refers to a patch file patches/llvm-project/0002-libc-Add-check-for-building-with-picolibc.patch but in the files availables in patches/llvm-project are:
- 0001-Fix-llvm-test-CodeGen-ARM-build-attributes.ll-test.patch	Unchanged	
- 0002-Add-check-for-building-with-picolibc.patch	Unchanged	
- 0003-Run-picolibc-tests-with-qemu.patch	Unchanged	
- 0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch	Unchanged

**Comment by domin144** [comment]
Hi @Laur59!
Thanks for spotting this. I will make a fix.
