### ISSUE TITLE
[CMakeLists] git command does not work on linux

### ISSUE THREAD

**Issue by sivan-shani** [ARM-software/LLVM-embedded-toolchain-for-Arm#404]
CMakeLists.txt instructs how to build by checking out and patch the repos manually.
In the instructions, the command:
`git -C repos/llvm-project am -k ../../patches/llvm-project/*.patch`
Does not work on Linux (probably because the the shell expands the '*' and not git)

**Comment by voltur01** [comment]
Hi Sivan,

You are right, looks like the pattern is expanded and used in different directories, thus the relative path is wrong in one of them. Providing the full path woks for me, e.g.

git -C repos/llvm-project am -k `pwd`/../patches/llvm-project/*.patch

I will update the doc, thank you for reporting this!
