### ISSUE TITLE
Build from source optimization

### ISSUE THREAD

**Issue by itxs** [ARM-software/LLVM-embedded-toolchain-for-Arm#469]
![image](https://github.com/user-attachments/assets/72deb5a1-0f5d-4db6-8cf3-195302f36070)
To speed up the build process, `--depth=1` parameter can be added to `git clone` command.

**Comment by voltur01** [comment]
Discussed in https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/471 and agreed not to update.
