### ISSUE TITLE
Relpath broken in custom build guide

### ISSUE THREAD

**Issue by itxs** [ARM-software/LLVM-embedded-toolchain-for-Arm#470]
![image](https://github.com/user-attachments/assets/a40bb05c-1883-4e17-a82f-9098a1efe4b2)

Paths with "$PWD"/../xxx should be actually just "$PWD"/xxx

**Comment by stuij** [comment]
fixed by https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/472
