### ISSUE TITLE
error: Failed to merge in the changes

### ISSUE THREAD

**Issue by AspenBen** [ARM-software/LLVM-embedded-toolchain-for-Arm#475]
I tried to compile the llvm myself,  so I download the code and follow the [guide](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/blob/main/docs/building-from-source.md)

but it occurred error that refer to the picture log, I have no idea what to do next.
![image](https://github.com/user-attachments/assets/783aa20d-0e23-4aad-b090-9d35cc4b7bcc)

I believe I have installed the necessary tool to compile.

**Comment by voltur01** [comment]
Hi, it looks like there is a merge conflict because of recent upstream changes, seems to be the same as this https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/issues/476 - we will look into updating this ASAP.

**Comment by statham-arm** [comment]
Believed fixed by #477.
