### ISSUE TITLE
Problem with upstream commit 917ada35

### ISSUE THREAD

**Issue by Laur59** [ARM-software/LLVM-embedded-toolchain-for-Arm#530]
Hello
In order to build the toolchain from the latest commits of upstream I need to use the following workaround:
Revert "[runtimes] Always define cxx_shared, cxx_static & other targets (#80007)"
(upstream commit 917ada35).
I presume that is needed in LLVM-ET-for-Arm CmakeLists.txt some lines to handle variables:
- LIBCXX_ENABLE_SHARED
- LIBUNWIND_ENABLE_SHARED

**Comment by dcandler** [comment]
Yes, a fix is incoming.
