### ISSUE TITLE
Is Apple clang version 12.0.5 available 

### ISSUE THREAD

**Issue by Guozhanxin** [ARM-software/LLVM-embedded-toolchain-for-Arm#57]
![image](https://user-images.githubusercontent.com/25633294/120486274-7bfd6d80-c3e7-11eb-9194-b1d5adb1fa69.png)
![image](https://user-images.githubusercontent.com/25633294/120486361-8c154d00-c3e7-11eb-9cc0-05ec03aaa60b.png)

Is Apple clang version 12.0.5 available ？

**Comment by voltur01** [comment]
Hi,

Building on macOS is not supported now. macOS support is expected in the future, however there is no particular timeline yet.
