### ISSUE TITLE
Releases page is empty

### ISSUE THREAD

**Issue by osmith42** [ARM-software/LLVM-embedded-toolchain-for-Arm#79]
`README.md` says:

> Download a release of the toolchain for your platform from [Github releases](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases) and extract the archive into an arbitrary directory.

However, when clicking the link:

> There aren’t any releases here

**Comment by voltur01** [comment]
Hi Oliver, thank you for reporting the issue and sorry for the current mismatch: the docs were updated for the first binary release, which will be published at the page in coming days.

**Comment by osmith42** [comment]
Okay, thank you.

**Comment by miyuki** [comment]
The 13.0.0 release has been uploaded, closing.
