### ISSUE TITLE
Error when compiling micro-ecc

### ISSUE THREAD

**Issue by zxtxin** [ARM-software/LLVM-embedded-toolchain-for-Arm#87]
I build micro-ecc with the following parameters:
`-std=c11 --config armv6m_soft_nofp_nosys.cfg -mno-unaligned-access -fshort-enums -fshort-wchar -g -ffunction-sections -fdata-sections -faapcs-bitfield-width -fno-common -Wall -Os`

It comes out that
![image](https://user-images.githubusercontent.com/5063358/149746522-12eb05ea-325f-4d58-a7bc-bf8b7d0a3560.png)

**Comment by voltur01** [comment]
The file referred to in the error message: https://github.com/kmackay/micro-ecc/blob/master/asm_arm.inc

**Comment by davemgreen** [comment]
Hello. Does adding -fomit-frame-pointer help? GCC will have that enabled by default (when not at -O0) where as clang will not, and that will lose you a register.

**Comment by smithp35** [comment]
I think the frame pointer is definitely it. Looking at the register trace in clang it r7 is reserved, and this block of inline asm needs every low register. I've checked that `-fomit-frame-pointer` will work, and gcc will not work with `-fno-omit-frame-pointer`

In the source file there is a .syntax divided line. Clang doesn't support that and at least my version gave an error message.

**Comment by momchil-velikov** [comment]
Yes, it compiles with `clang -target arm-eabi -march=armv6-m -std=c11 -mno-unaligned-access -fshort-enums -fshort-wchar  -ffunction-sections -fdata-sections -faapcs-bitfield-width -fno-common -Wall -Os -c -fomit-frame-pointer`
`
